export const mockChannels = [
	{
		channelId: 'asdf1234',
		name: '#general',
		createdAt: 123456,
		updatedAt: 123456,
		users: ['mtliendo'],
	},
	{
		channelId: 'efgt1234',
		name: '#job-opportunities',
		createdAt: 123456,
		updatedAt: 123456,
		users: ['mtliendo'],
	},
]

export const mockMessages = [
	{
		id: 1,
		createdAt: 1234445,
		channelId: 'asdf1234',
		updatedAt: 2334445,
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'I am the bottom',
	},
	{
		id: 2,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'asdf1234',
		username: 'focusotter',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
	{
		id: 3,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'asdf1234',
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content:
			'Here is some stuff \n and some more. Looks like some of the stuff is respected',
	},
	{
		id: 30,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'asdf1234',
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some other mock data to try out',
	},
	{
		id: 4,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'efgt1234',
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
	{
		id: 5,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'efgt1234',
		username: 'focusotter',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
	{
		id: 6,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'efgt1234',
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
	{
		id: 7,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'efgt1234',
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
	{
		id: 8,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'efgt1234',
		username: 'focusotter',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
	{
		id: 9,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'efgt1234',
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
	{
		id: 10,
		createdAt: 1234445,
		updatedAt: 2334445,
		channelId: 'efgt1234',
		username: 'mtliendo',
		profilePic: 'https://github.com/mtliendo.png',
		content: 'Here is some stuff \n and some more',
	},
]
